### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by fzyzcjy** [ProjectMapK/jackson-module-kogera#103]
Hi thanks for the package! I want to use value classes for various ids, say, `value class UserId(value: Long)` and so on. Thus, I wonder whether you suggest to use this library in production env?

**Comment by k163377** [comment]
Not recommended for production use.
This project is being developed privately and I will continue to implement experimental features without being willing to make destructive changes for some time.

If you want to use `value class` in your production code, `kotlinx.serialization` is probably your only option.

However, the features developed in this project will be incorporated into `jackson-module-kotlin` in the future, so your use and feedback are welcome.

**Comment by fzyzcjy** [comment]
@k163377 Thank you for the information! 

> If you want to use value class in your production code, kotlinx.serialization is probably your only option.

I see, thank you! However, my existing codebase is using jackson so I hope to use it ;)

> However, the features developed in this project will be incorporated into jackson-module-kotlin in the future

Good job and looking forward to it!
