### ISSUE TITLE
deserializer should return singleton instance for data object members

### ISSUE THREAD

**Issue by abop** [ProjectMapK/jackson-module-kogera#148]
**Object declarations**, as described in the Kotlin documentation: https://kotlinlang.org/docs/object-declarations.html#object-declarations-overview, are mainly used for the **Singleton** pattern. This is especially true for **data objects**, where all instances (even those generated using reflection) have the same `hashCode()` and `equals()` always returns `true`.

Therefore, I believe that when deserializing `data object` members, the serializer should return the singleton instance instead of creating a new one.

Here is a test case to demonstrate the issue:

```kotlin
@JsonTypeInfo(use = JsonTypeInfo.Id.MINIMAL_CLASS, include = JsonTypeInfo.As.PROPERTY)
sealed interface A

@JsonSubTypes.Type(value = EuropeanOptionFixingProps.Default::class)
data object B : A

data class C(val d: String) : A

data class D(val a: A)

fun main() {
    val mapper = ObjectMapper().findAndRegisterModules()

    val d = D(B)
    val json = mapper.writeValueAsString(d)
    val decoded = mapper.readValue<D>(json)

    // This should print "true true", but instead prints "true false".
    println("${decoded == d} ${decoded === d}")
}
```

**Comment by k163377** [comment]
Have you tried `SingletonSupport`?
Due to historical reasons, `jackson-module-kotlin` will not handle objects correctly unless you enable `SingletonSupport`.
`kogera` has a similar implementation.

```kotlin
import com.fasterxml.jackson.annotation.JsonTypeInfo
import com.fasterxml.jackson.databind.ObjectMapper

@JsonTypeInfo(use = JsonTypeInfo.Id.MINIMAL_CLASS, include = JsonTypeInfo.As.PROPERTY)
sealed interface A

object B : A

data class C(val d: String) : A

data class D(val a: A)

fun main() {
    val mapper = ObjectMapper().registerModule(KotlinModule.Builder().enable(KotlinFeature.SingletonSupport).build())

    val d = D(B)
    val json = mapper.writeValueAsString(d)
    val decoded = mapper.readValue<D>(json)

    // This should print "true true", but instead prints "true false".
    println("${decoded.a == d.a} ${decoded.a === d.a}")
}
```

By the way, in the sample code, `D`, the `data class`, is compared with `===`, which is always `false`, right?

**Comment by abop** [comment]
Thanks for your reply! I will try it out.

And yes, you’re right about the last “===“ comparison.

**Comment by abop** [comment]
> Have you tried `SingletonSupport`? Due to historical reasons, `jackson-module-kotlin` will not handle objects correctly unless you enable `SingletonSupport`. `kogera` has a similar implementation.
> 
> ```kotlin
> import com.fasterxml.jackson.annotation.JsonTypeInfo
> import com.fasterxml.jackson.databind.ObjectMapper
> 
> @JsonTypeInfo(use = JsonTypeInfo.Id.MINIMAL_CLASS, include = JsonTypeInfo.As.PROPERTY)
> sealed interface A
> 
> object B : A
> 
> data class C(val d: String) : A
> 
> data class D(val a: A)
> 
> fun main() {
>     val mapper = ObjectMapper().registerModule(KotlinModule.Builder().enable(KotlinFeature.SingletonSupport).build())
> 
>     val d = D(B)
>     val json = mapper.writeValueAsString(d)
>     val decoded = mapper.readValue<D>(json)
> 
>     // This should print "true true", but instead prints "true false".
>     println("${decoded.a == d.a} ${decoded.a === d.a}")
> }
> ```
> 
> By the way, in the sample code, `D`, the `data class`, is compared with `===`, which is always `false`, right?

It behaves as you said. Thanks for making ecosystem for kotlin better!
