### ISSUE TITLE
Deserializing value classes?

### ISSUE THREAD

**Issue by ZeroOne3010** [ProjectMapK/jackson-module-kogera#157]
Hi there,

I'm missing a proper example of deserializing a JSON document into something that has value classes... Let's take the following simplified example:
```json
{
  "id" : "Q1085",
  "type" : "item"
}
```

My class for it looks like this: 

```kotlin
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty

data class Item @JsonCreator constructor(
    @JsonProperty("id") val id: ItemId,
    @JsonProperty("type") val type: String,
)
```

and `ItemId` looks like this:
```kotlin
@JvmInline
value class ItemId(val id: String)
```

Yet, when I try to deserialize it with `ObjectMapper.readValue(String)` (the function referring to `io.github.projectmapk.jackson.module.kogera.readValue`), I only get this error:

```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `Item` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
```

I don't know what to make of this? I've also tried the value class with some extra annotations but with the same end result:
```kotlin
import com.fasterxml.jackson.annotation.JsonCreator
import io.github.projectmapk.jackson.module.kogera.annotation.JsonUnbox

@JvmInline
@JsonUnbox
value class ItemId @JsonCreator constructor(val id: String)
```

**Comment by k163377** [comment]
I tried with `2.15.2-beta5` but could not reproduce.
If you have any special settings in your mapper, please share them too.

```kotlin
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import io.github.projectmapk.jackson.module.kogera.jacksonObjectMapper
import io.github.projectmapk.jackson.module.kogera.readValue
import org.junit.jupiter.api.Test

class GitHub157 {
    @JvmInline
    value class ItemId(val id: String)

    data class Item @JsonCreator constructor(
        @JsonProperty("id") val id: ItemId,
        @JsonProperty("type") val type: String,
    )

    @Test
    fun test() {
        val json = """
            {
              "id" : "Q1085",
              "type" : "item"
            }
        """.trimIndent()
        val mapper = jacksonObjectMapper()

        val result = mapper.readValue<Item>(json)

        println(result) // -> Item(id=ItemId(id=Q1085), type=item)
    }
}
```

**Comment by ZeroOne3010** [comment]
Oh right, I can see the issue now! I had instantiated object mapper as `val objectMapper = ObjectMapper()`. It works when I use the `jacksonObjectMapper()` function instead. :ok_hand: Maybe consider adding that to the migration guide? Anyway, thanks for your quick help and your great work with this library, I'll just go ahead and close this issue!
