### ISSUE TITLE
`JsonDeserialize` annotation does not work for `value class` that is `unboxed` on the argument

### ISSUE THREAD

**Issue by k163377** [ProjectMapK/jackson-module-kogera#46]
Fixes #50 and #54 make it work except for the `JsonDeserialize` annotation when it is `unboxed` on the argument.

---

Below is the initial description.

## Annotation given to function arguments containing value class does not work
Annotations with `value class` as an argument are compiled into `synthetic` functions with markers and `private` functions without markers.
`Jackson` is handling the `private` function, but this function does not reflect the annotation given on `Kotlin`.
This prevents the associated content from working.

This problem can be avoided by modifying the annotations to be given to `getter`, etc.

```kotlin
// before
data class Data(@JsonSerialize(using = /* ... */) val value: ValueClass)

// fixed
data class Data(@get:JsonSerialize(using = /* ... */) val value: ValueClass)
```

As for the annotations that must be given as arguments, please wait until the problem is fixed.

**Comment by abop** [comment]
> Fixes #50 and #54 make it work except for the `JsonDeserialize` annotation when it is `unboxed` on the argument.
> 
> Below is the initial description.
> 
> ## Annotation given to function arguments containing value class does not work
> Annotations with `value class` as an argument are compiled into `synthetic` functions with markers and `private` functions without markers. `Jackson` is handling the `private` function, but this function does not reflect the annotation given on `Kotlin`. This prevents the associated content from working.
> 
> This problem can be avoided by modifying the annotations to be given to `getter`, etc.
> 
> ```kotlin
> // before
> data class Data(@JsonSerialize(using = /* ... */) val value: ValueClass)
> 
> // fixed
> data class Data(@get:JsonSerialize(using = /* ... */) val value: ValueClass)
> ```
> 
> As for the annotations that must be given as arguments, please wait until the problem is fixed.

```kotlin
    data class SummaryInfoReq(
        @get:JsonProperty("currency") val currency: Currency,
        @get:JsonProperty("vendor_net_pay") val vendorNetPay: BigDecimal,
    )
```
The `@JsonProperty` annotation works as expected (both when serializing and deserializing) when given to `getter`. 👏
