### ISSUE TITLE
Rename kotlin module in this project to be able to try it easily in other projects

### ISSUE THREAD

**Issue by Chuckame** [ProjectMapK/jackson-module-kogera#83]
Hey,

Your lib seems very nice, but hard to test since we have to make attention about dependencies, and we all know that it's quickly a nightmare to find the one (or those) that retrieve jackson-kotlin-module.

Can you rename it to avoid name clash ?

**Comment by k163377** [comment]
I intend to make the change by the end of this month.
https://github.com/ProjectMapK/jackson-module-kogera#about-the-future

**Comment by k163377** [comment]
Reschedule this change to be made at the time of transition to 2.15.

**Comment by k163377** [comment]
I apologize for the delay in responding due to my busy schedule.
I have released a version with corrected package names.
https://github.com/ProjectMapK/jackson-module-kogera/releases/tag/2.15.2-beta0
